### ISSUE TITLE
Errors msg on calculation of PET 

### ISSUE THREAD

**Issue by ML426** [CenterForTheBuiltEnvironment/pythermalcomfort#38] opened 2022-08-18 13:21 UTC
Hi,
Thanks for sharing pythermal.

I have a concern though, I am trying to calculate PET values using pet_steady however I am getting a warning message but I don't know if the source is from the pythermalcomfort models or the method I used to calculate PET values on python pandas.

below the line of code and the error messages

` M['PET']=M.apply(lambda x: pet_steady(tdb=x['Tmrt'], tr=x['Ta'], rh=x['RH'], v=x['v'], age=35, height=1.75,met=1.48, clo=0.9), axis=1)
`

_C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\minpack.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last five Jacobian evaluations.

C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\minpack.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning
  warnings.warn(msg, RuntimeWarning)_

Regards,
ML

**Comment by FedericoTartarini** [comment] 2022-09-08 07:28
Hi, I do not think the issue is caused by pythermalcomfort but instead it appears to be caused by the code you wrote. The warning message is from ipkernel. Please try to pass the inputs to the pet_steady function as Numpy arrays or lists. This will return an array that you can assign to M["PET"]. Please let me know if this solves the problem.

**Closed by FedericoTartarini** 2022-09-08 07:28 UTC
