### ISSUE TITLE
Encountering Problem in calling python functions through MATLAB 

### ISSUE THREAD

**Issue by livingelectron** [CenterForTheBuiltEnvironment/pythermalcomfort#62] opened 2023-06-17 08:47 UTC
I have created a m-script file by calling Pyhton Modules the code is given below:-
tdb = 25;
tr = 25;
rh = 50;
v = 0.1;
met = 1.4;
clo = 0.5;
v_r=py.pythermalcomfort.utilities.v_relative(v=v, met=met);
clo_d=py.pythermalcomfort.utilities.clo_dynamic(clo=clo, met=met);
pmv=py.pythermalcomfort.pmv_ppd(tdb=tdb, tr=tr, vr=v_r, rh=rh, met=met, clo=clo_d);
display(pmv)

The output of the code is perfect as expected which is as follows:-
pmv = 
  Python dict with no properties.
    {'pmv': 0.06, 'ppd': 5.1}

Now i am trying to create a Simulink Block using this m-script Code. I am using MATLAB function block for this and put the following code in the MATLAB functon code generator block:-
function PMV = PMV_BLOCK(tdb, tr, vr, rh, met, clo)
tdb = 25;
tr = 25;
rh = 50;
v = 0.1;
met = 1.4;
clo = 0.5;
coder.extrinsic('py.pythermalcomfort.utilities.v_relative', 'py.pythermalcomfort.utilities.clo_dynamic','py.pythermalcomfort.pmv_ppd')
v_r=py.pythermalcomfort.utilities.v_relative(v=v, met=met);
clo_d=py.pythermalcomfort.utilities.clo_dynamic(clo=clo, met=met);
pmvc=py.pythermalcomfort.pmv_ppd(tdb=tdb, tr=tr, vr=v_r, rh=rh, met=met, clo=clo_d)
PMV=double(0);
PMV = pmvc;

when i run this program following error is displayed:-
Python Error: TypeError: v_relative() takes 2 positional arguments but 4 were given Error in 'PMV_Block/PMV Calculator' (line 9) v_r=py.pythermalcomfort.utilities.v_relative(v=v, met=met);

I don't know why this python error is coming although the code is running fine in MATLAB m-script file. I am using a third party Python module. ANy urgent help in this regard will be greatly appreciated.

**Comment by FedericoTartarini** [comment] 2023-06-19 02:07
I am not entirely sure what is causing the error since it looks like it is an issue with MATLAB. Try to ignore the relative air speed calculation for now. If that works then I would recommend you just coping the source code in MATLAB that is used to calculate the relative air speed since it is a very simple equation.

**Comment by FedericoTartarini** [comment] 2023-06-19 02:08
I am closing this comment since the issue is not actually related to pythermalcomfort but it is actually related to MATLAB symulink

**Closed by FedericoTartarini** 2023-06-19 02:08 UTC
