### ISSUE TITLE
Unit error in sweat rate function for PET

### ISSUE THREAD

**Issue by QINQINKONG** [CenterForTheBuiltEnvironment/pythermalcomfort#95] opened 2024-01-14 07:35 UTC
**Describe the bug**
Hi, thanks for this great package!
There seem to be an unit error in the sweat_rate function for calculating PET. The error occurs in the following line:

m_rsw = 304.94 * 10**-3 * sig_body

where the "10**-3" shouldn't be there.

This is expected to cause substantial biases when sweat is required for cooling.

**Comment by FedericoTartarini** [comment] 2024-01-14 22:17
Thank you so much for pointing this out, I did not personally write the PET code so I was not aware of this issue. Could you please provide a screenshot or the original reference to the PET code so I can also check the other lines of the code?

**Comment by QINQINKONG** [comment] 2024-01-15 08:11
Hi. The code is based on this paper: https://doi.org/10.1016/j.buildenv.2018.03.054. The authors originally deposit their code at here: https://github.com/eddes/AREP/blob/master/steady_PET.py#L133.
However, it seems that both their original code and the code in pythermalcomfort have this unit issue. The sweat rate function is called to calculate evaporative cooling:
qmsw = sweat_rate(tbody)
esw = h_vap / 1000 * qmsw / 3600  # [W/m2]
where qmsw should have the unit of g/m^2/h. However, "304.94 * 10**-3 * sig_body" produce the unit of kg/m^2/h.

**Comment by FedericoTartarini** [comment] 2024-01-15 22:33
Thank you so much for pointing this out, I forwarded your issue to Walther Edouard one of the authors of the paper, the same person who wrote the Python code. I will wait for his response and then I will fix the issue in the code.

**Comment by eddes** [comment] 2024-01-17 12:29
Hi there,
Thank you @QINQINKONG for your acute reviewing of the code: it is indeed a mistake in the unit (back in the days we had converted all constants in SI units on some version of the code). 
The latent heat of vaporization is indeed Lv = 2400 [J/g] so the rest of the computation remains coherent.
I will update the eddes/AREP/ repo.
Best regards,

**Comment by FedericoTartarini** [comment] 2024-01-17 22:38
Hi @QINQINKONG thank you again for spotting the issue. I have already fixed in the code and soon I will publish a new version of pythermalcomfort once I have solved the following issue. I really appreciate your help.

@eddes I was fixing the code and I am now getting this `DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future.`. This is caused by the fact that in your code you convert the t_arr to a multidimensional array but then you are accessing it like this t_arr[1, 0]. It is not clear to me why the t_arr is a multidimensional array. May I ask you why you decided to combine [T_core, T_sk, T_clo] in one single array and why not using np.array but creating a two-dimensional array instead here: t_arr = np.reshape(t_arr, (3, 1)). Thank you so much for your help.

**Comment by FedericoTartarini** [comment] 2024-01-17 22:41
I also would like to point out that the change that @QINQINKONG has suggested is changing the output of the model. I had some tests in place and the results are changing as follows:
* pet_steady(tdb=30, tr=30, rh=50, v=0.15, met=1.37, clo=0.5) changes from 30.59 to 30.6
* pet_steady(tdb=30, tr=60, rh=80, v=1.0, met=1.37, clo=0.9) changes from 43.05 to 44.63
* pet_steady(tdb=30, tr=30, rh=80, v=1.0, met=1.37, clo=0.9) changes from 31.69 to 32.21

**Comment by eddes** [comment] 2024-01-18 08:46
> @eddes I was fixing the code and I am now getting this `DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future.`. This is caused by the fact that in your code you convert the t_arr to a multidimensional array but then you are accessing it like this t_arr[1, 0]. It is not clear to me why the t_arr is a multidimensional array. May I ask you why you decided to combine [T_core, T_sk, T_clo] in one single array and why not using np.array but creating a two-dimensional array instead here: t_arr = np.reshape(t_arr, (3, 1)). Thank you so much for your help.

Hi Federico,
Good point: I suppose we were doing this because of our beginner-level in python back then!
I had a try removing both the reshape of t_arr and the array for energy balances enbal_vec
#t_arr = np.reshape(t_arr, (3, 1))
#enbal_vec=np.zeros((3,1))

So t_arr[i,0] is simply replaced by t_arr[i].

Then the energy budget on each node is as follows (in my code T is your t_arr)
enbal_vec0 = h + ere - (vasoC(T[0],T[1])[0]/3600*cb+5.28)*(T[0]-T[1]) # Core balance [W/m^2]
enbal_vec1 = rbare + cbare + evap + (vasoC(T[0],T[1])[0]/3600*cb+5.28)*(T[0]-T[1]) - htcl*(T[1]-T[2])  # Skin balance [W/m^2]
enbal_vec2 = cclo + rclo + htcl*(T[1]-T[2]) # Clothes balance [W/m^2]

and as a return of the function it is simply :
if mode==True:
        # if we solve for the system we need to return 3 temperatures
        return np.array([enbal_vec0,enbal_vec1,enbal_vec2])

This solves the deprecation warning.
Regards,

**Comment by eddes** [comment] 2024-01-18 08:47
> I also would like to point out that the change that @QINQINKONG has suggested is changing the output of the model. I had some tests in place and the results are changing as follows:
> 
> * pet_steady(tdb=30, tr=30, rh=50, v=0.15, met=1.37, clo=0.5) changes from 30.59 to 30.6
> * pet_steady(tdb=30, tr=60, rh=80, v=1.0, met=1.37, clo=0.9) changes from 43.05 to 44.63
> * pet_steady(tdb=30, tr=30, rh=80, v=1.0, met=1.37, clo=0.9) changes from 31.69 to 32.21

Yes I also noticed a change of the order of magnitude of 1 degree. Given the width of the PET thermal sensation ranges, especially in hot environments, it should not drastically change results.

**Comment by QINQINKONG** [comment] 2024-01-18 13:22
Great! Thank you all for this great python package and such quick response!
Best,
-Qin
________________________________

**Comment by FedericoTartarini** [comment] 2024-01-18 23:43
@eddes great to know, I removed the array altogether since the temperatures can simply be a list. I tested the code and everything seems to be fine.

I published pythermalcomfort version 2.9.1

**Closed by FedericoTartarini** 2024-01-18 23:43 UTC
